classes :
  @sylma-classbase : \sylma\dom
  handler :
    name : basic\handler\Rooted
  document :
    name : basic\Document
  element :
    name : basic\Element
  attribute :
    name : basic\Attribute
  collection :
    name : basic\Collection
  fragment :
    name : basic\Fragment
  text :
    name : basic\Text
  comment :
    name : basic\Comment
  argument :
    file : argument/Tokened.php
    name : argument\Tokened
    classes :
      filed :
        file : argument/Filed.php
        name : argument\Filed
stats :
  enable : false
namespaces :
  html : http://www.w3.org/1999/xhtml
  dom : http://www.sylma.org/dom
import-depth : 5